#pragma once
enum PACKET_OP_CODE
{
    OP_LPR_STREAM = 1,
    OP_CONTEXT_STREAM = 2,
    OP_RECOGNITION_RESULT = 7,
    OP_ZB_BASICINFO = 30,
    OP_ZB_ZFIPT_MOVE,
    OP_ZB_WATCHME,
    OP_ZB_POWERSET,
    OP_ZB_GPS_RMC,
    OP_ZB_GPS_GSV,
    OP_ZB_MONITOR_INFO,
    OP_LPR_CAM_COMMAND,
    OP_CONTEXTCAM_COMMAND,
    OP_DEBUG_STREAM1 = 40,
    OP_DEBUG_STREAM2,
    OP_CONNECT_AUTH,
    OP_AUTO_BRIGHTNESS,
    OP_ZB_IRIS,
    OP_ZB_NIGHT_MODE,
    OP_AUTO_IRIS,
    OP_INIT_STATUS_REQ,
    OP_PANTILT_COMMAND,
    OP_TRIGGER_STATUS,
    OP_USER_UART_INIT,
    OP_USER_UART_RAW,
    OP_ZB_UART_DATA,
    OP_LENS_STATUS,
    OP_STREAM_ONOFF,
    OP_STREAM_FRAME_SET,
    OP_SOFTWARE_TRIGGER,
    OP_ALIVE_CHECK,
    OP_RESULT_TIMEDELAY,
    OP_AUTO_FOCUS_SET,
    OP_BOARD_SET,
    OP_CRACKDOWN_SET,
    OP_PANTILT_PRESET,
    OP_AUTO_MANUAL_ONOFF
};

enum AUTO_MANUAL_ONOFF
{
    SET_MANUAL_AUTO,
    GET_MANUAL_AUTO
};

enum PANTILT_PRESET
{
    SET_PNATILT_PRESET,
    SET_CALL_PANTILT_PRESET,
    GET_CALL_PANTILT_PRESET
};

enum CRACKDOWN_ONOFF
{
    SET_CRACKDOWN_DATA,
    GET_CRACKDOWN_DATA
};

enum BOARD_DATA
{
    SET_BOARD_DATA,
    GET_BOARD_DATA,
    SET_BOARD_POWER,
    GET_BOARD_POWER,
    SET_DISPLAY_ONOFF,
    GET_DISPLAY_ONOFF
};

enum RESULT_TIMEDELAY
{
    SET_TIMEDELAY,
    GET_TIMEDELAY
};

enum STREAM_ONOFF
{
    SET_LPR_STREAM_ONOFF,
    GET_LPR_STREAM_ONOFF,
    SET_CONTEXT_STREAM_ONOFF,
    GET_CONTEXT_STREAM_ONOFF
};

enum STREAM_FRAME
{
    SET_LPR_STREAM_FRAME,
    GET_LPR_STREAM_FRAME,
    SET_CONTEXT_STREAM_FRAME,
    GET_CONTEXT_STREAM_FRAME
};

enum LENS_STATUS
{
    LENS_STATUS_SAVE,
    LENS_STATUS_LOAD,
    LENS_STATUS_INIT
};

enum TIRGGER_STATUS
{
    SET_TRIGGER_STATUS,
    GET_TRIGGER_STATUS
};

enum WATCH_ME
{
    SET_WATCHME,
    GET_WATCHME
};

enum LENS_MOVE
{
    SET_ABS_ZOOM = 1,
    SET_RELATIVE_ZOOM,
    SET_MOVE_ZOOM,
    SET_STOP_ZOOM,
    GET_ZOOM_VALUE,
    SET_ABS_FOCUS,
    SET_RELATIVE_FOCUS,
    SET_MOVE_FOCUS,
    SET_STOP_FOCUS,
    GET_FOCUS_VALUE
};

enum PANTILT_COMMAND
{
    SET_OFF,
    SET_UP,
    SET_DOWN,
    SET_LEFT,
    SET_RIGHT,
    SET_UP_LEFT,
    SET_UP_RIGHT,
    SET_DOWN_LEFT,
    SET_DOWN_RIGHT,
    SET_LOCK_FREE
};

enum POWER_SET_COMMAND{
    SET_PRO_UNIT,
    GET_PRO_UNIT,
    SET_USB_HUB,
    GET_USB_HUB,
    SET_LASER,
    GET_LASER,
    SET_GPS,
    GET_GPS,
    SET_FLASH,
    GET_FLASH
};

enum IRIS_COMMAND
{
    SET_ABS_IRIS = 1,
    SET_RELATIVE_IRIS,
    SET_MOVE_IRIS,
    SET_STOP_IRIS,
    GET_IRIS_VALUE
};

enum NIGHT_MODE_COMMAND{
    SET_NIGHT_MODE,
    GET_NIGHT_MODE
};

enum AUTO_IRIS_COMMAND{
    SET_AUTO_IRIS_MODE,
    GET_AUTO_IRIS_MODE
};

enum LPR_CAM_COMMAND { 
    SET_LPR_GAIN = 0,
    GET_LPR_GAIN,
    SET_LPR_EXPOSURE,
    GET_LPR_EXPOSURE,
    SET_LPR_TARGET_BR,
    GET_LPR_TARGET_BR,
    SET_LPR_AUTOGAIN,
    GET_LPR_AUTOGAIN,
    SET_LPR_AUTOEXPOSURE,
    GET_LPR_AUTOEXPOSURE,
    SET_AUTO_GAIN_LOWER,
    GET_AUTO_GAIN_LOWER,
    SET_AUTO_GAIN_UPPER,
    GET_AUTO_GAIN_UPPER,
    SET_AUTO_EXPOSURE_LOWER,
    GET_AUTO_EXPOSURE_LOWER,
    SET_AUTO_EXPOSURE_UPPER,
    GET_AUTO_EXPOSURE_UPPER,
    SET_LPR_OVERLAPMODE,
    GET_LPR_OVERLAPMODE,
    SET_LPR_AUTOFUNCTION_PROFILE,
    GET_LPR_AUTOFUNCTION_PROFILE,
    SET_LPR_CONTRAST_ENHANCEMENT,
    GET_LPR_CONTRAST_ENHANCEMENT,
    SET_DEFECT_PIXEL_CORRECTION_MODE,
    GET_DEFECT_PIXEL_CORRECTION_MODE,
    SET_BACKLIGHT_COMPENSATION,
    GET_BACKLIGHT_COMPENSATION,
    SET_LPR_REVERSE_Y,
    GET_LPR_REVERSE_Y,
    SET_LPR_REVERSE_X,
    GET_LPR_REVERSE_X,
    SET_DEVICE_LINK_THROUGHPUT_LIMIT_MODE,
    GET_DEVICE_LINK_THROUGHPUT_LIMIT_MODE,
    SET_DEVICE_LINK_THROUGHPUT_LIMIT,
    GET_DEVICE_LINK_THROUGHPUT_LIMIT,
    SET_DEVICE_INDICATOR_MODE,
    GET_DEVICE_INDICATOR_MODE,
    SET_TRIGGER_MODE,
    GET_TRIGGER_MODE,
    SET_TRIGGER_SOURCE,
    GET_TRIGGER_SOURCE,
    SET_TRIGGER_ACTIVATION,
    GET_TRIGGER_ACTIVATION,
    SET_LINE_SELECTOR,
    GET_LINE_SELECTOR,
    SET_LINE_MODE,
    GET_LINE_MODE,
    SET_LINE_INVETER,
    GET_LINE_INVETER,
    SET_ACQUISTION_RATE,
    GET_ACQUISTION_RATE
};

enum AUTO_BRIGHT_COMMAND{
    SET_AUTO_BRIGHTNESS,
    GET_AUTO_BRIGHTNESS
};

enum CONTEXT_CAM_COMMAND{
    SET_CONTEXT_GAIN =0, 
    GET_CONTEXT_GAIN, 
    SET_CONTEXT_EXPOSURE, 
    GET_CONTEXT_EXPOSURE, 
    SET_CONTEXT_AUTOGAIN, 
    GET_CONTEXT_AUTOGAIN, 
    SET_CONTEXT_AUTOEXPOSURE,
    GET_CONTEXT_AUTOEXPOSURE,
    SET_CONTEXT_REVERSE_Y,
    GET_CONTEXT_REVERSE_Y,
    SET_CONTEXT_REVERSE_X,
    GET_CONTEXT_REVERSE_X
};

